keys:
  - &ruby 1d62493ab34a45e22d728ebcefd1b0c8c5b76dda
  - &gateway 51ef34681bcddc37351da26e02faf6f5e6407234
  - &opal-entrypoint e1894e81323ea0aaee2fbb7609bd7a85015e0848
creation_rules:
  - path_regex: secrets/gateway\.yaml$
    key_groups:
    - pgp:
      - *ruby
      - *gateway
  - path_regex: secrets/opal-entrypoint\.yaml$
    key_groups:
      - pgp:
        - *ruby
        - *opal-entrypoint
