#!/usr/bin/env fish

function show_help
  echo "pls - A simple NixOS system management helper"
  echo ""
  echo "Usage: pls [COMMAND]"
  echo "Commands:"
  echo "  help: Show this output"
  echo "  build: Rebuild NixOS and switch"
  echo "  test: Rebuild NixOS, but don't switch"
  echo "  clean: Run the Nix garbage collector and optimize the store"
  echo "  search: Search Nixpkgs for a package"
  echo "  update: Update Nixpkgs and other flake dependencies"
  echo "  upgrade: Equivalent to `pls build && pls clean`"
  exit 1
end

set -l rebuild (switch (uname -s)
  case "Linux"
    echo "nixos-rebuild --use-remote-sudo"
  case "Darwin"
    echo "darwin-rebuild"
end)

switch $argv[1]
  case build
    eval $rebuild -L --show-trace --flake ~/nixos switch
    rm result > /dev/null 2>&1
  case test
    eval $rebuild -L --show-trace --flake ~/nixos test
    rm result > /dev/null 2>&1
  case clean
    sudo nix-collect-garbage -d
    nix store optimise
  case search
    nix search nixpkgs $argv[2..]
  case update
    nix flake update --flake ~/nixos
  case upgrade
    pls update && pls build
  case '*'
    show_help
end
